firefox: Update to 51.0b7 (WIP)
It still fails to execute configure:

  checking for link... not found
  DEBUG: link: Trying 'arm-poky-linux-gnueabi-ld --sysroot=/home/aho/Projects/rz-g-bsp/build-wayland/tmp/sysroots/skrzg1e '
  ERROR: Cannot find link

It's caused by following lines in build/moz.configure/windows.configure:

  link = check_prog('LINK', depends_win()(lambda: ('link.exe',)), input='LD',
                    paths=vc_compiler_path)

Signed-off-by: Takuro Ashie <ashie@homa.ne.jp>